[package]
name    = "rolldown_testing"
version = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
edition.workspace    = true
homepage.workspace   = true
license.workspace    = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
rolldown_common = { workspace = true, features = ["deserialize_bundler_options"] }
sugar_path      = { workspace = true }

[build-dependencies]
rolldown_common = { workspace = true, features = ["deserialize_bundler_options"] }
schemars        = { workspace = true }
serde_json      = { workspace = true }
