[package]
name = "rolldown_plugin_copy_module"
version = "0.1.0"
edition.workspace = true
license = "MIT"
publish = true
description = "Rolldown builtin plugin implementing esbuild copy loader semantics"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
arcstr = { workspace = true }
memchr = { workspace = true }
rolldown_common = { workspace = true }
rolldown_plugin = { workspace = true }
rolldown_utils = { workspace = true }
rustc-hash = { workspace = true }
string_wizard = { workspace = true }
sugar_path = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
