[package]
edition.workspace    = true
homepage.workspace   = true
license.workspace    = true
name                 = "rolldown_plugin_glob_import"
repository.workspace = true
version              = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
async-trait     = { workspace = true }
glob            = { workspace = true }
oxc             = { workspace = true }
rolldown_plugin = { workspace = true }
sugar_path      = { workspace = true }
