[package]
name = "rolldown_plugin_vite_css"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = true
repository.workspace = true
description = "Rolldown plugin for Vite CSS handling"

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
base64-simd = { workspace = true }
derive_more = { workspace = true }
rolldown_plugin = { workspace = true }
rolldown_plugin_utils = { workspace = true }
rolldown_sourcemap = { workspace = true }
rolldown_utils = { workspace = true }
rustc-hash = { workspace = true }
serde_json = { workspace = true }
