[package]
edition.workspace    = true
homepage.workspace   = true
license.workspace    = true
name                 = "rolldown_plugin"
repository.workspace = true
version              = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
async-trait        = { workspace = true }
futures            = { workspace = true }
rolldown_common    = { workspace = true }
rolldown_error     = { workspace = true }
rolldown_fs        = { workspace = true }
rolldown_resolver  = { workspace = true }
rolldown_sourcemap = { workspace = true }
rolldown_utils     = { workspace = true }
tracing            = { workspace = true }
