[package]
name = "rolldown_plugin"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[features]
default = ["serde"]
serde = ["dep:serde", "oxc_index/serde"]

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
arcstr = { workspace = true }
async-trait = { workspace = true }
dashmap = { workspace = true }
derive_more = { workspace = true, features = ["display"] }
oxc_index = { workspace = true }
rolldown_common = { workspace = true }
rolldown_debug = { workspace = true }
rolldown_ecmascript = { workspace = true }
rolldown_error = { workspace = true }
rolldown_resolver = { workspace = true }
rolldown_sourcemap = { workspace = true }
rolldown_utils = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true, optional = true }
string_wizard = { workspace = true }
sugar_path = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true, features = ["valuable"] }
typedmap = { workspace = true, features = ["dashmap"] }
valuable = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["serde"]
