[package]
name = "rolldown_plugin_css"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
repository.workspace = true
description = "Rolldown built-in CSS bundling plugin"

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
arcstr = { workspace = true }
derive_more = { workspace = true }
grass = { workspace = true }
lightningcss = { workspace = true }
parcel_sourcemap = { workspace = true }
parking_lot = { workspace = true }
regex = { workspace = true }
rolldown_common = { workspace = true }
rustc-hash = { workspace = true }
rolldown_plugin = { workspace = true }
rolldown_plugin_utils = { workspace = true }
rolldown_sourcemap = { workspace = true }
rolldown_utils = { workspace = true }
sugar_path = { workspace = true }
