[package]
edition.workspace    = true
homepage.workspace   = true
license.workspace    = true
name                 = "rolldown_testing_config"
repository.workspace = true
version              = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonschema      = { workspace = true }
once_cell       = { workspace = true }
rolldown_common = { workspace = true, features = ["deserialize_bundler_options"] }
schemars        = { workspace = true }
serde           = { workspace = true, features = ["derive"] }
serde_json      = { workspace = true }


[lints]
workspace = true
