[package]
name = "rolldown_plugin_chunk_import_map"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
doctest = false

[dependencies]
arcstr = { workspace = true }
rolldown_common = { workspace = true }
rolldown_plugin = { workspace = true }
rolldown_utils = { workspace = true }
rustc-hash = { workspace = true }
serde_json = { workspace = true }
xxhash-rust = { workspace = true, features = ["xxh3"] }
