[package]
name = "rolldown_plugin_oxc_runtime"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[lib]
doctest = false

[dependencies]
arcstr = { workspace = true }
phf = { workspace = true }
rolldown_plugin = { workspace = true }
rolldown_utils = { workspace = true }

[build-dependencies]
oxc_resolver = { workspace = true }
