[package]
name = "rolldown_plugin_vite_resolve"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
# NOTE: IDNA support is turned off: https://docs.rs/crate/idna_adapter/latest#:~:text=Turning%20off%20IDNA%20support
arcstr = { workspace = true }
cow-utils = { workspace = true }
derive_more = { workspace = true }
fast-glob = { workspace = true }
oxc_resolver = { workspace = true, features = ["package_json_raw_json_api"] }
rolldown_common = { workspace = true }
rolldown_plugin = { workspace = true }
rolldown_plugin_utils = { workspace = true }
rolldown_utils = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sugar_path = { workspace = true }
url = { workspace = true }
urlencoding = { workspace = true }
