[package]
edition.workspace    = true
homepage.workspace   = true
license.workspace    = true
name                 = "rolldown_plugin_vite_scanner"
repository.workspace = true
version              = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
async-trait     = { workspace = true }
dashmap         = { workspace = true }
once_cell       = { workspace = true }
regex           = { workspace = true }
rolldown_fs     = { workspace = true }
rolldown_plugin = { workspace = true }
rustc-hash      = { workspace = true }
