[package]
name                 = "rolldown_plugin_vite_scanner"
version              = "0.1.0"
edition.workspace    = true
homepage.workspace   = true
license.workspace    = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
rolldown_plugin = { path = "../rolldown_plugin" }
rolldown_error  = { path = "../rolldown_error" }
rolldown_fs     = { path = "../rolldown_fs" }
async-trait     = { workspace = true }
regex           = { workspace = true }
once_cell       = { workspace = true }
rustc-hash      = { workspace = true }
dashmap         = { workspace = true }
