[package]
name = "rolldown_plugin_reporter"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
cow-utils = { workspace = true }
flate2 = { workspace = true }
itoa = { workspace = true }
num-format = { workspace = true }
rayon = { workspace = true }
rolldown_common = { workspace = true }
rolldown_plugin = { workspace = true }
rolldown_plugin_utils = { workspace = true }
sugar_path = { workspace = true }
terminal_size = { workspace = true }
