[package]
name = "rolldown_plugin_isolated_declaration"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
oxc = { workspace = true }
rolldown_common = { workspace = true }
rolldown_error = { workspace = true }
rolldown_plugin = { workspace = true }
rolldown_utils = { workspace = true }
sugar_path = { workspace = true }

[dev-dependencies]
rolldown_testing = { workspace = true }
testing_macros = { workspace = true }
