[package]
name = "rolldown_resolver"
version = "0.1.0"
description = "rolldown_resolver"

edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
arcstr = { workspace = true }
dashmap = { workspace = true }
itertools = { workspace = true }
oxc_resolver = { workspace = true }
rolldown_common = { workspace = true }
rolldown_fs = { workspace = true, features = ["os"] }
rolldown_utils = { workspace = true }
sugar_path = { workspace = true }
