[package]
name    = "bench"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
edition.workspace    = true
homepage.workspace   = true
license.workspace    = true
repository.workspace = true

[lib]
bench   = false
doctest = false
test    = false

[dependencies]
codspeed-criterion-compat = { workspace = true }
rolldown                  = { path = "../rolldown" }
tokio                     = { workspace = true, features = ["full"] }
[[bench]]
harness = false
name    = "threejs"
