[package]
name    = "bench"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
homepage.workspace   = true
license.workspace    = true
edition.workspace    = true
repository.workspace = true

[lib]
bench = false

[dependencies]
criterion = "0.4.0"
rolldown  = { path = "../rolldown" }
tokio     = { workspace = true, features = ["full"] }
rolldown_fs = { path = "../rolldown_fs/" }
[[bench]]
name    = "threejs"
harness = false


[dev-dependencies]
codspeed-criterion-compat = "2.3.1"
