[package]
description = "rolldown_tracing"
name        = "rolldown_tracing"
version     = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

edition.workspace    = true
homepage.workspace   = true
license.workspace    = true
repository.workspace = true

[lints]
workspace = true

[lib]
bench   = false
doctest = false
test    = false

[dependencies]
tracing            = { workspace = true }
tracing-chrome     = "0.7.1"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
