[package]
name = "rolldown_plugin_chunk_visualize"
version = "0.1.0"
edition.workspace = true
license = "MIT"
publish = true
description = "Rolldown plugin for generating chunk visualization data"

[lib]
doctest = false

[dependencies]
arcstr = { workspace = true }
rolldown_common = { workspace = true }
rolldown_plugin = { workspace = true }
rolldown_utils = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sugar_path = { workspace = true }
