[package]
name = "rolldown_plugin_import_glob"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
fast-glob = { workspace = true }
itoa = { workspace = true }
oxc = { workspace = true }
rolldown_ecmascript_utils = { workspace = true }
rolldown_plugin = { workspace = true }
rolldown_plugin_utils = { workspace = true }
rolldown_utils = { workspace = true }
sugar_path = { workspace = true }
walkdir = { workspace = true }
