[package]
name = "rolldown_watcher"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
description = "Watcher for rolldown with state machine-based implementation"

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
arcstr = { workspace = true }
oxc_index = { workspace = true }
rolldown = { path = "../rolldown", features = ["experimental"] }
rolldown_common = { workspace = true }
rolldown_error = { workspace = true }
rolldown_fs_watcher = { workspace = true }
rolldown-notify = { workspace = true }
rolldown_utils = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros", "sync", "time"] }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros", "sync", "rt-multi-thread", "signal"] }
