[package]
name    = "rolldown_sourcemap"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

edition.workspace    = true
homepage.workspace   = true
license.workspace    = true
repository.workspace = true

[lints]
workspace = true

[lib]
bench   = false
doctest = false
test    = false

[dependencies]
oxc            = { workspace = true }
rolldown_error = { path = "../rolldown_error" }
rustc-hash     = { workspace = true }
