[package]
name = "rolldown_sourcemap"
version = "0.1.0"
publish = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[lib]
bench = false
doctest = false

[dependencies]
memchr = { workspace = true }
oxc = { workspace = true }
oxc_sourcemap = { workspace = true }
rolldown_utils = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]
criterion2 = { workspace = true, default-features = false }

[[bench]]
harness = false
name = "join"
