[package]
edition.workspace    = true
homepage.workspace   = true
license.workspace    = true
name                 = "ls-lint"
repository.workspace = true
version              = "0.1.0"

[dependencies]
anyhow             = { workspace = true }
globset            = "0.4"
heck               = { workspace = true }
ignore             = "0.4"
rolldown_workspace = { workspace = true }
serde              = { workspace = true }
serde_json         = { workspace = true }

[lints]
workspace = true
