[package]
edition.workspace    = true
homepage.workspace   = true
license.workspace    = true
name                 = "gen-options"
repository.workspace = true
version              = "0.1.0"

[dependencies]
anyhow           = { workspace = true }
cow-utils        = { workspace = true }
heck             = { workspace = true }
rolldown_testing = { workspace = true }
regex            = { workspace = true }

prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
# quote = { workspace = true }
syn = { workspace = true, features = [
  "clone-impls",
  "derive",
  "extra-traits",
  "full",
  "parsing",
  "printing",
  "proc-macro",
] }

[lints]
workspace = true
