[package]
name = "rolldown_plugin_data_url"
version = "0.1.0"
edition.workspace = true
license = "MIT"
publish = true
description = "Rolldown plugin for data URI handling"

[lib]
doctest = false

[dependencies]
arcstr = { workspace = true }
base64-simd = { workspace = true }
rolldown_common = { workspace = true }
rolldown_plugin = { workspace = true }
rolldown_utils = { workspace = true }
simdutf8 = { workspace = true }
urlencoding = { workspace = true }
