name: 'autofix.ci'
on:
  # https://github.com/actions/labeler?tab=readme-ov-file#permissions
  pull_request_target:
    types: [labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  autofix_ci:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'autofix.ci'
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: ./.github/actions/setup-node

      - uses: ./.github/actions/setup-rust
        with:
          tools: just, taplo-cli, cargo-shear
          cache-key: debug-build
          components: clippy rustfmt

      - run: |
          just fix
          just ued

      - uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef

      - uses: actions-cool/issues-helper@a610082f8ac0cf03e357eb8dd0d5e2ba075e017e # v3.6.0
        with:
          actions: 'remove-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          labels: 'autofix.ci'
