name: 'Automation Stale Bot'

permissions: {}

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          days-before-stale: 30
          days-before-close: -1 # We don't want to close stale issues and PRs automatically
          # --- issues
          stale-issue-message: ''
          stale-issue-label: 'stale'
          # --- PRs
          stale-pr-message: "This PR is considered stale and will be convert to draft soon. Please undraft it if you think it's ready to be reviewed."
          stale-pr-label: 'stale'
          close-pr-message: '' # We don't want to close stale PRs automatically, so this is commented out
          exempt-draft-pr: true # We don't want to mark draft PRs as stale
