name: Cache Warmup

permissions: {}

on:
  push:
    branches:
      - main
    paths:
      - '**/*.rs'
      - 'Cargo.lock'

# Only do cache warmup on main branch's latest commit
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  debug-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Warmup for debug build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1

      - name: Setup Rust
        uses: oxc-project/setup-rust@d286d43bc1f606abbd98096666ff8be68c8d5f57 # v1.0.2
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          cache-key: debug-build
          tools: just

      - name: Setup Node For Development
        uses: ./.github/actions/setup-node

      - run: cargo check --workspace
      - run: cargo test --workspace --no-run
      - run: just build-rolldown

  release-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Warmup for release build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1

      - name: Setup Rust
        uses: oxc-project/setup-rust@d286d43bc1f606abbd98096666ff8be68c8d5f57 # v1.0.2
        with:
          cache-key: release-build
          save-cache: ${{ github.ref_name == 'main' }}
          tools: just

      - name: Setup Node For Development
        uses: ./.github/actions/setup-node

      - run: just build-rolldown-release

  debug-build-wasi:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Warmup for debug build with WASI target
    runs-on: ${{ matrix.os }}
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1

      - name: Setup Rust
        uses: oxc-project/setup-rust@d286d43bc1f606abbd98096666ff8be68c8d5f57 # v1.0.2
        with:
          cache-key: debug-build-wasi
          save-cache: ${{ github.ref_name == 'main' }}

      - name: Add WASI target
        run: rustup target add wasm32-wasip1-threads

      - run: cargo check --workspace
      - run: cargo test --workspace --no-run
