name: Mergeability check

permissions: {}

on:
  pull_request:
    types: [opened, assigned, unassigned]
  merge_group:

jobs:
  require-assignee-approval:
    name: Check assignees' approval
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1

      - name: Check assignees' approval
        uses: hyf0/action-require-assignee-approval@a3980039f1f53ec199135983eef2b33bcff2f201 # v1.0.0
        with:
          allow-no-assign: true # optional, default is `true`
          bypass-by: github-actions[bot]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
