# https://github.com/stackblitz-labs/pkg.pr.new
name: Publish to pkg.pr.new

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  build:
    if: >
      github.repository == 'rolldown/rolldown' &&
      (github.event_name == 'workflow_call' || github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'trigger: preview')))
    name: Build bindings and node packages
    uses: ./.github/workflows/reusable-release-build.yml
    with:
      version: 'commit'

  publish:
    if: >
      github.repository == 'rolldown/rolldown' &&
      (github.event_name == 'workflow_call' || github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'trigger: preview')))
    name: Pkg Preview
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Git Reset Hard
        run: git reset --hard # fix pnpm install add new line for package.json

      - name: Download Binding Artifacts
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          path: packages/rolldown/artifacts

      - name: Move Binding Artifacts
        run: pnpm --filter rolldown artifacts

      - name: List Rolldown Bindings
        run: ls -R ./packages/rolldown/npm
        shell: bash

      - name: Download Node Artifacts
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          path: packages/rolldown/dist
          name: node-artifact

      - name: Download `rolldown-version.txt`
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          name: rolldown-version

      - name: Read `rolldown-version.txt`
        id: rolldown-version
        uses: igorskyflyer/action-readfile@d38a0aef4a6ba5245f2a127705a8cdc8d5d5e702 # v1.0.0
        with:
          path: rolldown-version.txt

      - name: Canary/Nightly Versioning
        run: node --import @oxc-node/core/register ./scripts/misc/bump-version.js ${{ steps.rolldown-version.outputs.content }}

      - name: Copy Licenses
        run: |
          find ./packages/ -type d -maxdepth 1 -exec cp LICENSE {} \;
          find ./packages/ -type d -maxdepth 1 -exec cp THIRD-PARTY-LICENSE {} \;

      - name: Release
        run: pnpx pkg-pr-new publish --compact --pnpm './packages/rolldown/npm/*' './packages/rolldown'
