name: Build Rolldown with WASI Binding

permissions: {}

on:
  workflow_call:
    inputs:
      changed:
        required: true
        type: boolean

jobs:
  run:
    name: Build Rolldown with WASI Binding
    if: ${{ inputs.changed }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          submodules: true
          persist-credentials: false

      - name: Setup Rust
        uses: oxc-project/setup-rust@eb5c2bf64ce11cc9557c576d6766c164d064fdb7 # v1.0.10
        with:
          tools: just
          cache-key: debug-build-wasi

      - uses: oxc-project/setup-node@141eb77546de6702f92d320926403fe3f9f6a6f2 # v1.0.5

      - name: Add WASI target
        run: rustup target add wasm32-wasip1-threads

      - name: Build Rolldown with WASI Binding
        run: just build-rolldown-wasi

      - name: Upload Rolldown with WASI Binding
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: rolldown-wasi
          path: |
            packages/rolldown/dist
            packages/pluginutils/dist
          if-no-files-found: error
