name: Build Rolldown with WASI Binding

permissions: {}

on:
  workflow_call:
    inputs:
      changed:
        required: true
        type: boolean

jobs:
  run:
    name: Build Rolldown with WASI Binding
    if: ${{ inputs.changed }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true
          persist-credentials: false

      - name: Setup Rust
        uses: oxc-project/setup-rust@d286d43bc1f606abbd98096666ff8be68c8d5f57 # v1.0.2
        with:
          tools: just
          cache-key: debug-build-wasi

      - uses: oxc-project/setup-node@fdbf0dfd334c4e6d56ceeb77d91c76339c2a0885 # v1.0.4

      - name: Add WASI target
        run: rustup target add wasm32-wasip1-threads

      - name: Build Rolldown with WASI Binding
        run: just build-rolldown-wasi

      - name: Upload Rolldown with WASI Binding
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: rolldown-wasi
          path: |
            packages/rolldown/dist
            packages/pluginutils/dist
          if-no-files-found: error
