name: Node Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      changed:
        required: true
        type: boolean

jobs:
  run:
    name: Node Test
    if: ${{ inputs.changed }}
    runs-on: ${{ inputs.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true # Pull submodules for additional files

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          tools: just
          cache-key: debug-build

      - name: Setup Node For Development
        uses: ./.github/actions/setup-node

      - name: Build Native Rolldown
        run: just build native

      - name: Type Check
        run: pnpm type-check

      - name: Setup Node18 For Testing
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 18

      - name: Node Test For Node18
        run: |
          pnpm run --filter rolldown-tests test:main && pnpm run --filter rolldown-tests test:watcher && pnpm run --filter rolldown-tests test:stability

      - name: Rollup Test Node18
        run: pnpm run --filter rollup-tests test

      - name: Build Examples For Node18
        run: pnpm --filter '@example/**' build

      - name: Setup Node20 For Testing
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 20

      - name: Node Test For Node20
        run: |
          pnpm run --filter rolldown-tests test:main && pnpm run --filter rolldown-tests test:watcher && pnpm run --filter rolldown-tests test:stability

      - name: Rollup Test Node20
        run: pnpm run --filter rollup-tests test

      - name: Build Examples For Node20
        run: pnpm --filter '@example/**' build

      - name: Setup Node22 For Testing
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 22

      - name: Node Test For Node22
        run: |
          pnpm run --filter rolldown-tests test:main && pnpm run --filter rolldown-tests test:watcher && pnpm run --filter rolldown-tests test:stability

      - name: Rollup Test Node22
        run: pnpm run --filter rollup-tests test

      - name: Build Examples For Node22
        run: pnpm --filter '@example/**' build
