name: Rust Test

permissions: {}

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      changed:
        required: true
        type: boolean

jobs:
  run:
    if: ${{ inputs.changed }}
    name: Cargo Test
    runs-on: ${{ inputs.os }}
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1

      - name: Setup Rust
        uses: oxc-project/setup-rust@eb5c2bf64ce11cc9557c576d6766c164d064fdb7 # v1.0.10
        with:
          tools: just
          cache-key: debug-build

      - uses: oxc-project/setup-node@141eb77546de6702f92d320926403fe3f9f6a6f2 # v1.0.5

      - name: Build
        run: cargo test --workspace --exclude rolldown_binding --no-run

      - name: Run Test
        run: just test-rust
        env:
          # Reject updated snapshots https://insta.rs/docs/advanced/#controlling-snapshot-updating
          INSTA_UPDATE: no
