name: Node Test

permissions: {}

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      changed:
        required: true
        type: boolean

jobs:
  run:
    name: Node Test
    if: ${{ inputs.changed }}
    runs-on: ${{ inputs.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true # Pull submodules for additional files
          persist-credentials: false

      - name: Setup Rust
        uses: oxc-project/setup-rust@c8224157c0bf235aabc633e8cd50d344f087a7de # v1.0.12
        with:
          tools: just

      - uses: oxc-project/setup-node@8958a8e040102244b619c4a94fccb657a44b1c21 # v1.0.6

      - name: Download Native Rolldown Build
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: rolldown-native-${{ inputs.os }}
          path: ./packages

      - name: Build `@rolldown/test-dev-server`
        run: pnpm --filter '@rolldown/test-dev-server' build

      - name: Type Check
        run: pnpm type-check

      - name: Node Type Test
        run: |
          pnpm run --filter rolldown-tests test:types

      - name: Setup Node20 For Testing
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 20
          package-manager-cache: false

      - name: Node Test For Node20
        run: |
          pnpm run --filter rolldown-tests test:main && pnpm run --filter rolldown-tests test:watcher && pnpm run --filter rolldown-tests test:stability

      - name: Rollup Test For Node20
        run: pnpm run --filter rollup-tests test
        env:
          SKIP_PASS_DIFF: 1

      - name: Build Examples For Node20
        run: pnpm --filter '@example/**' build

      - name: Setup Node22 For Testing
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 22
          package-manager-cache: false

      - name: Node Test For Node22
        run: |
          pnpm run --filter rolldown-tests test:main && pnpm run --filter rolldown-tests test:watcher && pnpm run --filter rolldown-tests test:stability

      - name: Rollup Test For Node22
        run: pnpm run --filter rollup-tests test
        env:
          SKIP_PASS_DIFF: 1

      - name: Build Examples For Node22
        run: pnpm --filter '@example/**' build

      - name: Setup Node24 For Testing
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24
          package-manager-cache: false

      - name: Node Test For Node24
        run: |
          pnpm run --filter rolldown-tests test:main && pnpm run --filter rolldown-tests test:watcher && pnpm run --filter rolldown-tests test:stability

      - name: Rollup Test For Node24
        run: pnpm run --filter rollup-tests test

      - name: Build Examples For Node24
        run: pnpm --filter '@example/**' build
