name: Node Test

permissions: {}

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      changed:
        required: true
        type: boolean

jobs:
  run:
    name: Node Test
    if: ${{ inputs.changed }}
    runs-on: ${{ inputs.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          submodules: true # Pull submodules for additional files
          persist-credentials: false

      - name: Setup Rust
        uses: oxc-project/setup-rust@eb5c2bf64ce11cc9557c576d6766c164d064fdb7 # v1.0.10
        with:
          tools: just
          cache-key: debug-build

      - uses: oxc-project/setup-node@141eb77546de6702f92d320926403fe3f9f6a6f2 # v1.0.5

      - name: Build Native Rolldown
        run: just build-rolldown

      - name: Check no diff
        run: git diff --exit-code

      - name: Build `@rolldown/test-dev-server`
        run: pnpm --filter '@rolldown/test-dev-server' build

      - name: Type Check
        run: pnpm type-check

      - name: Node Type Test
        run: |
          pnpm run --filter rolldown-tests test:types

      - name: Setup Node20 For Testing
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 20
          package-manager-cache: false

      - name: Node Test For Node20
        run: |
          pnpm run --filter rolldown-tests test:main && pnpm run --filter rolldown-tests test:watcher && pnpm run --filter rolldown-tests test:stability

      - name: Rollup Test For Node20
        run: pnpm run --filter rollup-tests test

      - name: Build Examples For Node20
        run: pnpm --filter '@example/**' build

      - name: HMR Test For Node20
        run: pnpm run --filter '@rolldown/test-dev-server-tests' test

      - name: Setup Node22 For Testing
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 22
          package-manager-cache: false

      - name: Node Test For Node22
        run: |
          pnpm run --filter rolldown-tests test:main && pnpm run --filter rolldown-tests test:watcher && pnpm run --filter rolldown-tests test:stability

      - name: Rollup Test For Node22
        run: pnpm run --filter rollup-tests test

      - name: Build Examples For Node22
        run: pnpm --filter '@example/**' build

      - name: HMR Test For Node22
        run: pnpm run --filter '@rolldown/test-dev-server-tests' test

      - name: Setup Node24 For Testing
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24
          package-manager-cache: false

      - name: Node Test For Node24
        run: |
          pnpm run --filter rolldown-tests test:main && pnpm run --filter rolldown-tests test:watcher && pnpm run --filter rolldown-tests test:stability

      - name: Rollup Test For Node24
        run: pnpm run --filter rollup-tests test

      - name: Build Examples For Node24
        run: pnpm --filter '@example/**' build

      - name: HMR Test For Node24
        run: pnpm run --filter '@rolldown/test-dev-server-tests' test
