name: Rust Test

permissions: {}

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      changed:
        required: true
        type: boolean

jobs:
  run:
    if: ${{ inputs.changed }}
    name: Cargo Test
    runs-on: ${{ inputs.os }}
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1

      - name: Setup Rust
        uses: oxc-project/setup-rust@d286d43bc1f606abbd98096666ff8be68c8d5f57 # v1.0.2
        with:
          tools: just
          cache-key: debug-build

      - uses: oxc-project/setup-node@fdbf0dfd334c4e6d56ceeb77d91c76339c2a0885 # v1.0.4

      - name: Build
        run: cargo test --workspace --exclude rolldown_binding --no-run

      - name: Run Test
        run: just test-rust
        env:
          # Reject updated snapshots https://insta.rs/docs/advanced/#controlling-snapshot-updating
          INSTA_UPDATE: no
