name: Vite tests

permissions: {}

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'crates/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'rust-toolchain.toml'
      - '.gitattributes'
      - 'packages/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - '!packages/bench/**'
      - '!packages/debug/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  vite-tests:
    name: Vite Tests
    strategy:
      matrix:
        target: [ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.target }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          submodules: true # Pull submodules for additional files
          persist-credentials: false

      - name: Setup Rust
        uses: oxc-project/setup-rust@eb5c2bf64ce11cc9557c576d6766c164d064fdb7 # v1.0.10
        with:
          tools: just
          cache-key: debug-build

      - uses: oxc-project/setup-node@141eb77546de6702f92d320926403fe3f9f6a6f2 # v1.0.5

      - name: Build Native Rolldown
        run: just build-rolldown

      - name: Run Vite Tests
        run: pnpm run --filter vite-tests test
